### ISSUE TITLE
Migrate desktop UI to web

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/lockstacks#1]
Migrate all existing Stacking functionality from the desktop wallet to this web app, adding a new landing page for introducing new users and authenticating them.

**Comment by markmhx** [comment]
@mica000 mind linking the Figma designs here for the initial-release implementation of the Stacking app?

**Comment by mica000** [comment]
@markmhx I believe this was a FE only ticket to migrate the library

**Comment by markmhx** [comment]
Hm which library? My understanding is that this issue is for copying / migrating all the UX for Stacking that's currently in the desktop wallet into the new web app (for direct stackers and poolers alike), with adjustments and additions like the initial landing page (since the user needs a way to get started with the app).

**Comment by mica000** [comment]
@markmhx Got it! In that case, here are the links :)

[Prototype](https://www.figma.com/proto/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?page-id=6818%3A40809&node-id=7029%3A89325&viewport=1444%2C1287%2C0.31&scaling=contain&starting-point-node-id=7029%3A89325&show-proto-sidebar=1)

[Landing page](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=6910%3A61486&t=00gkXe2qCqElxgyq-4)

[Stacking by yourself](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=6983%3A440686&t=00gkXe2qCqElxgyq-4)

[Stacking in a pool](https://www.figma.com/file/VcXbxT1EwXvE1nUlOiBEES/Wallet-(%F0%9F%92%BF-desktop)?node-id=6986%3A82069&t=00gkXe2qCqElxgyq-4)
