### ISSUE TITLE
Create NFTs gallery page

### ISSUE THREAD

**Issue by markmhx** [hirosystems/lockstacks#10]
For displaying the Stacks NFTs and Ordinals that are owned by an array of STX and BTC taproot addresses as provided via the page's URL parameter(s)

We should wire up the page's metadata for robust previews when sharing or embedding elsewhere

**Comment by edu-stx** [comment]
[Notion doc](https://www.notion.so/trustmachines/Ordinals-support-0469c5cb4ad14b1e8df303981993c749#f3f8267d12ee4f038212c3384f37da6c)

**Comment by friedger** [comment]
Out of scope for lockstacks
