### ISSUE TITLE
BTC address should not be editable for non-ledger users for Planbetter

### ISSUE THREAD

**Issue by planbetterHQ** [hirosystems/lockstacks#108]
Planbetter pool has a different note in the Bitcoin address than Xverse. Please, we should have the same as Xverse.
![image](https://user-images.githubusercontent.com/89087989/231989427-8ce83064-013d-4ff9-9d94-a40a9b750d6d.png)

**Comment by markmhx** [comment]
What's the message shown for Xverse?

**Comment by friedger** [comment]
The message is not shown if the address is not editable

**Comment by markmhx** [comment]
Mind explaining this issue a bit more? With Planbetter, the user can edit the address value so we have this message, but Planbetter doesn't want to show it? Whereas with Xverse, it's not shown because it's not editable?

**Comment by markmhx** [comment]
Note as well the type that we should fix in any case: "control" instead of "controll"

**Comment by friedger** [comment]
addressed in #112
