### ISSUE TITLE
Create NFT page

### ISSUE THREAD

**Issue by markmhx** [hirosystems/lockstacks#11]
Display details for an NFT, whether Ordinal inscription or Stacks-based

We should wire up the page's metadata for robust previews when sharing or embedding elsewhere

**Comment by mica000** [comment]
https://www.figma.com/file/OSQocEEJnfcMkniEl8u3U8/%231483---Initial-Bitcoin-support?node-id=1203%3A61703&t=0OeOFKmcaHOATyvZ-4

**Comment by markmhx** [comment]
@mica000 did you mean to share the above design on a different, wallet-specific issue vs here for the web app?

**Comment by mica000** [comment]
@markmhx Oh! Nevermind! Got confused haha

**Comment by friedger** [comment]
Out of scope of lockstacks
