### ISSUE TITLE
Inform user about sip-22

### ISSUE THREAD

**Issue by friedger** [hirosystems/lockstacks#114]
With the upcoming SIP-22, we need to disable all stacking activity and inform the user about the why and how

Following information should the message contain:
* emergency issue with stacks-increase
* do not interact with pox2 now
* see that stx unlocks with Stacks 2.2, enjoy your liquid STX
* wait until pox-3 is live and available here - expected date: 10th May
* no rewards for # 58
* explain issue in more detail for curious readers with link to other resources

**Comment by markmhx** [comment]
@friedger it may be best if you wing a design change here re: disabling the relevant buttons and providing a link that takes users to a FAQ elsewhere? I can get the FAQ set up if you can provide the copy. In the app itself perhaps we just need a single line next to any disabled feature e.g. "Features are disabled while the Stacking protocol undergoes an emergency fix. Learn more"
