### ISSUE TITLE
show minimum delegation amount

### ISSUE THREAD

**Issue by friedger** [hirosystems/lockstacks#128]
If a pool member wants to increase the user needs to revoke ans re-delegate.

When delegating again, the user should be informed about the current locking so that the user can make an informed decision about the increase.

**Comment by friedger** [comment]
Suggested UI:

![image](https://github.com/hirosystems/lockstacks/assets/1449049/cc9ceff8-b276-433a-a1f0-2d1f4e9c2629)

**Comment by 314159265359879** [comment]
Instead of "minimum delegation amount" what about this
"Minimum amount": 5,499 STX?

instead of "This amount..."
The minimum amount is what is already stacked. For continuous stacking, you will have to pool this amount or more.
