### ISSUE TITLE
Enable Lock More again for direct stackers

### ISSUE THREAD

**Issue by friedger** [hirosystems/lockstacks#137]
With Stacks 2.4, stack-increase was enabled again.

The current modal says it is still disabled:
![image](https://github.com/hirosystems/lockstacks/assets/1449049/eff57859-c659-44ae-87d6-162658e396e4)

**Comment by GAD2511** [comment]
Hi, is Top up fx enabled at Friedger Pool level already?

**Comment by friedger** [comment]
Yes, pools can extend.
