### ISSUE TITLE
Change Xverse Logo to the New One on Lockstacks Website

### ISSUE THREAD

**Issue by GAD2511** [hirosystems/lockstacks#138]
On Lockstacks.com, Xverse old logo is set up while Xverse has new Logo now.
Here is how you can see it:
lockstacks.com > Connect Wallet > Stack in Pool
![Screenshot 2023-06-29 at 16-49-26 Stacking](https://github.com/hirosystems/lockstacks/assets/62007848/0c272285-75a0-4161-afb2-9370ceb148e9)

It might be good to change to the new one
Find out the new Logo on [www.xverse.app](url)/ Press Kit.

**Comment by markmhx** [comment]
Sounds good. @GAD2511 mind providing the exact asset we should use here?

**Comment by QUDBS** [comment]
> Sounds good. @GAD2511 mind providing the exact asset we should use here?
You can use this one @markmhx 

![xverse_icon](https://github.com/hirosystems/lockstacks/assets/99788136/5cc43910-2dfa-470f-a44d-97641ba74a3a)
