### ISSUE TITLE
Add explanation that less may be stacked

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/lockstacks#140]
In FAST pools, and possibly others, less than the asked about is stacked. I was confused 1 STX less than the sum was stacked. This happens to allow some remaining STX for fees, however some explanation to the user would be helpful

**Comment by friedger** [comment]
Something like this?
![image](https://github.com/hirosystems/lockstacks/assets/1449049/9110c69b-a088-4fa1-a392-266e8c2239e0)

Is that too verbose? @markmhx

**Comment by markmhx** [comment]
LGTM 💪
