### ISSUE TITLE
Improve delegation length UX and selection

### ISSUE THREAD

**Issue by edu-stx** [hirosystems/lockstacks#15]
See https://github.com/hirosystems/stacking/pull/7#issuecomment-1408662060

**Comment by friedger** [comment]
The importance of delegation length has changed with pox-2 for pools.
All current pools lock only for 1 cycle independent of the duration of the pool membership (delegation length).

There is a potential use case for individual settings of the delegation length: Users might want to plan their latest exit of a pool, like in a year or so. (If you swim for too long, you might grow fins :-))

The UI should make clear that the stx CAN be unlocked after each cycle. At least for current pools, this is true.

**Comment by friedger** [comment]
Addressed in #148
