### ISSUE TITLE
Set indefinite duration as initial value for pooled stacking

### ISSUE THREAD

**Issue by friedger** [hirosystems/lockstacks#30]
As the duration is of less importance in Stacks 2.1, we should help the user and set it to indefinite

**Comment by markmhx** [comment]
IIRC the duration is selected as indefinite for users already. Do you mean providing extra guidance on why this selection should be a strong preference unless the user has very particular needs, perhaps minimizing the presence of limited stacking further?

**Comment by friedger** [comment]
Users have to click. The initial type is undefined.

If I set the type to indefinite in the code and then the user changes to limited, then the initial number of cycles is 0. 

With the current types for the duration (typescript) I don't know how to solve this in clean code.

**Comment by markmhx** [comment]
@edu-stx might have an idea for how we can set indefinite as a default choice here and avoid the initial number issue you describe, though this enhancements seems like a nice-to-have for launch so let's not sweat it too much

**Comment by planbetterHQ** [comment]
The duration section doesn't make sense for us either. If people choose our pool, they choose indefinite permission too. Duration section should be fixed and non-modifiable or just hidden.
![image](https://user-images.githubusercontent.com/89087989/231988033-f7c5aeb3-1d18-4c59-b916-73dfc5b815ac.png)

**Comment by friedger** [comment]
It should be up to the pool to decide whether to show it or not.

**Comment by friedger** [comment]
Related https://github.com/hirosystems/btcweb3/issues/15

**Comment by markmhx** [comment]
> It should be up to the pool to decide whether to show it or not.

Should we start thinking of a config file with all the various pools' preferences or something? To make these customizations easiest to manage

**Comment by friedger** [comment]
5he config is defined by the Pool type

**Comment by friedger** [comment]
Another customer support chat, here for reference:
> When I previously used the Hiro Desktop wallet I selected "indefinite". Is selecting that irrelevant now since it has to be re-stacked after every cycle? Is there a negative consequence to selecting indefinite?

"indefinite" is the default and means that you want to be part of the pool until you revoke/stop pooling.
"limited" means that you want to be part of the pool until at most the provided duration or until you revoke before that provided time.
