### ISSUE TITLE
Add pool admin page for solo stackers

### ISSUE THREAD

**Issue by friedger** [hirosystems/lockstacks#80]
It would be nice to add a pool admin page for solo stackers as a pool. The idea is that the main balance is in a cold storage and delegated to a pool address that is a hot wallet and controlled by the same user.

The page has
* a form to delegate-stack-stx at `pool-admin/delegate-stack-stx`
* a form to stack-aggregation-commit at `pool-admin/stack-aggregation-commit`

**Comment by friedger** [comment]
See https://github.com/hirosystems/btcweb3/pull/84

**Comment by friedger** [comment]
This functionality has been implemented.

Do we want to make it more accessible for solo stackers who want to use a cold wallet and a hot wallet? @markmhx 

I suggest to add a info box for solo stackers with a link to the admin page.

**Comment by markmhx** [comment]
@friedger sounds good, though for now can we drop in a simple link somewhere for relevant users?
